name: kyouha_nani
description: "AIを使わずにオフラインで読める、365日の日めくりと毎日の壁紙アプリ。"
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: 6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/wallpapers/
